### ISSUE TITLE
Latest Update cause issues (post on Factorio)

### ISSUE THREAD

**Issue by SGZ-Creations** [powercrystals/grand-unified-factorio-theory#6]
https://mods.factorio.com/mod/grand-unified-factorio-theory/discussion/63b94e716d9086a342d19eda

**Comment by SGZ-Creations** [comment]
Here is a fix that u can upload to the portal. It's totally up to you. Look at & see. The fix i did by some help from the bob's Discord.
[grand-unified-factorio-theory_1.0.16.zip](https://github.com/powercrystals/grand-unified-factorio-theory/files/10372749/grand-unified-factorio-theory_1.0.16.zip)

**Comment by powercrystals** [comment]
Sorry, I've been out on vacation last week. I'll take a look when I get a chance. I don't suppose you're able to format this as a PR? If so it'd make it super easy for me, otherwise I'm sure I can figure it out when I get there.

**Comment by powercrystals** [comment]
No problem at all on the notifications. I will take a look at that (and also that 248k issue reported, uh, like 6 months ago) when I get there but it might be a day or three before all that gets done depending on my schedule.

**Comment by SGZ-Creations** [comment]
ok crash part fixed that's good hope u get the rest too.
